# Generated by Django 3.2.3 on 2021-05-23 02:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='id',
        ),
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.UUIDField(default='2395031590be456b9971a82c34bc981c', editable=False, help_text='Post ID', primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='PostComments',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default='a675e64759f34673b0c86f3ad107967b', editable=False, help_text='Post Comment ID', primary_key=True, serialize=False)),
                ('body', models.TextField(verbose_name='Body Title')),
                ('post', models.ForeignKey(help_text='Post', on_delete=django.db.models.deletion.CASCADE, to='backend.post')),
                ('user', models.ForeignKey(help_text='User', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
