# Generated by Django 3.2.3 on 2021-05-23 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20210522_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.UUIDField(default='0bcf09742b4f405d8623da873abb9d75', editable=False, help_text='Post ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='postcomments',
            name='body',
            field=models.TextField(verbose_name='Body'),
        ),
        migrations.AlterField(
            model_name='postcomments',
            name='id',
            field=models.UUIDField(default='6f0beccb37804706b4748b6f684bac44', editable=False, help_text='Post Comment ID', primary_key=True, serialize=False),
        ),
    ]
