# Generated by Django 3.2.3 on 2021-05-29 05:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20210522_2319'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Post ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='postcomments',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Post Comment ID', primary_key=True, serialize=False),
        ),
    ]
